language: java

sudo: false

install: true

jdk: 
      -oraclejdk8
      -oraclejdk7

script: mvn test

      
notifications:
  email:
    recipients:
    - qureshm@tcd.ie
    - erlist@tcd.ie
    - eozoani@tcd.ie
    - muganc@tcd.ie
    - crawford@tcd.ie
    on_success: always
    on_failure: always 
    
    
    
cache: bundler

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  os:
  - linux
  - osx

